baseURL = "/hugo-hero-theme"
languageCode = "en-us"
title = "Chemical Sciences Society"
themesDir = "../.."
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Chemical Sciences Society is a registered society in NUS. We help the Department of Chemistry organise events for Chemistry undergraduates. "
    meta_og_title = "Chemical Sciences Society"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Test Site"
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
	name = "Our Structure"
	url = "/structure/"
    weight = 1

[[menu.main]]
    name = "Past Events"
    url = "/events/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
